# Default initial positions for CLOVIS2Mini's ros2_control fake system

initial_positions:
  R0_AxisRz_Waist_Yaw: 0.0
  R1_AxisRx_Abs_Roll: 0.0
  R2_AxisRy_Abs_Pitch: 0.0
  R10_AxisRy_Hips_Flexion: 0.0
  R11_AxisRx_Hips_Abduction: 0.0
  R12_AxisRz_Hips_Rotation: 0.0
  R13_AxisRy_Knee_Flexion: 0.0
  R14_AxisRy_Ankle_Flexion: 0.0
  R15_AxisRx_Ankle_Abduction: 0.0
  R16_AxisRx_Toe_Flexion: 0.0
  R20_AxisRy_Hips_Flexion: 0.0
  R21_AxisRx_Hips_Abduction: 0.0
  R22_AxisRz_Hips_Rotation: 0.0
  R23_AxisRy_Knee_Flexion: 0.0
  R24_AxisRy_Ankle_Flexion: 0.0
  R25_AxisRx_Ankle_Abduction: 0.0
  R26_AxisRx_Toe_Flexion: 0.0
  R30_AxisRy_Shoulder_Flexion: 0.0
  R31_AxisRz_Shoulder_Rotation: 0.0
  R32_AxisRx_Shoulder_Abduction: 0.0
  R33_AxisRy_Elbow_Flexion: 0.0
  R34_AxisRz_Wrist_Rotation: 0.0
  R35_AxisRx_Wrist_Abduction: 0.0
  R40_AxisRy_Shoulder_Flexion: 0.0
  R41_AxisRz_Shoulder_Rotation: 0.0
  R42_AxisRx_Shoulder_Abduction: 0.0
  R43_AxisRy_Elbow_Flexion: 0.0
  R44_AxisRz_Wrist_Rotation: 0.0
  R45_AxisRx_Wrist_Abduction: 0.0
