# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - torso_controller
    - left_leg_controller
    - right_leg_controller

  torso_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - R0_AxisRz_Waist_Yaw
      - R1_AxisRx_Waist_Roll
      - R2_AxisRy_Abs_Pitch

  left_leg_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - R10_AxisRy_Hips_Flexion
      - R11_AxisRx_Hips_Abduction
      - R12_AxisRz_Hips_Rotation
      - R13_AxisRy_Knee_Flexion
      - R14_AxisRy_Ankle_Flexion
      - R15_AxisRx_Ankle_Abduction
      - R16_AxisRx_Toe_Flexion

  right_leg_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - R20_AxisRy_Hips_Flexion
      - R21_AxisRx_Hips_Abduction
      - R22_AxisRz_Hips_Rotation
      - R23_AxisRy_Knee_Flexion
      - R24_AxisRy_Ankle_Flexion
      - R25_AxisRx_Ankle_Abduction
      - R26_AxisRx_Toe_Flexion
