# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - torso_controller
    - left_leg_controller
    - right_leg_controller
    - left_arm_controller
    - right_arm_controller

  torso_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - R0_AxisRz_Waist_Yaw
      - R1_AxisRx_Abs_Roll
      - R2_AxisRy_Abs_Pitch

  left_leg_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - R10_AxisRy_Hips_Flexion
      - R11_AxisRx_Hips_Abduction
      - R12_AxisRz_Hips_Rotation
      - R13_AxisRy_Knee_Flexion
      - R14_AxisRy_Ankle_Flexion
      - R15_AxisRx_Ankle_Abduction
      - R16_AxisRx_Toe_Flexion

  right_leg_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - R20_AxisRy_Hips_Flexion
      - R21_AxisRx_Hips_Abduction
      - R22_AxisRz_Hips_Rotation
      - R23_AxisRy_Knee_Flexion
      - R24_AxisRy_Ankle_Flexion
      - R25_AxisRx_Ankle_Abduction
      - R26_AxisRx_Toe_Flexion

  left_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - R30_AxisRy_Shoulder_Flexion
      - R31_AxisRz_Shoulder_Rotation
      - R32_AxisRx_Shoulder_Abduction
      - R33_AxisRy_Elbow_Flexion
      - R34_AxisRz_Wrist_Rotation
      - R35_AxisRx_Wrist_Abduction

  right_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - R40_AxisRy_Shoulder_Flexion
      - R41_AxisRz_Shoulder_Rotation
      - R42_AxisRx_Shoulder_Abduction
      - R43_AxisRy_Elbow_Flexion
      - R44_AxisRz_Wrist_Rotation
      - R45_AxisRx_Wrist_Abduction
