# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    torso_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    left_leg_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    right_leg_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

torso_controller:
  ros__parameters:
    joints:
      - R0_AxisRz_Waist_Yaw
      - R1_AxisRx_Waist_Roll
      - R2_AxisRy_Abs_Pitch
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
left_leg_controller:
  ros__parameters:
    joints:
      - R10_AxisRy_Hips_Flexion
      - R11_AxisRx_Hips_Abduction
      - R12_AxisRz_Hips_Rotation
      - R13_AxisRy_Knee_Flexion
      - R14_AxisRy_Ankle_Flexion
      - R15_AxisRx_Ankle_Abduction
      - R16_AxisRx_Toe_Flexion
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
right_leg_controller:
  ros__parameters:
    joints:
      - R20_AxisRy_Hips_Flexion
      - R21_AxisRx_Hips_Abduction
      - R22_AxisRz_Hips_Rotation
      - R23_AxisRy_Knee_Flexion
      - R24_AxisRy_Ankle_Flexion
      - R25_AxisRx_Ankle_Abduction
      - R26_AxisRx_Toe_Flexion
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
