controller_manager:
  ros__parameters:
    update_rate: 100 #Hz
    use_sim_time: true

    torso_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    left_leg_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    right_leg_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    left_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    right_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

torso_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - R0_AxisRz_Waist_Yaw
      - R1_AxisRx_Abs_Roll
      - R2_AxisRy_Abs_Pitch
    state_publish_rate: 50.0
    action_monitor_rate: 20.0

    allow_partial_joints_goal: true
    hardware_state_has_offset: true
    deduce_states_from_derivatives: true

    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0

    gains:
      R0_AxisRz_Waist_Yaw: {p: 100.0, i: 0.01, d: 1.0}
      R1_AxisRx_Abs_Roll: {p: 100.0, i: 0.01, d: 1.0}
      R2_AxisRy_Abs_Pitch: {p: 100.0, i: 0.01, d: 1.0}

left_leg_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - R10_AxisRy_Hips_Flexion
      - R11_AxisRx_Hips_Abduction
      - R12_AxisRz_Hips_Rotation
      - R13_AxisRy_Knee_Flexion
      - R14_AxisRy_Ankle_Flexion
      - R15_AxisRx_Ankle_Abduction
      - R16_AxisRx_Toe_Flexion
    state_publish_rate: 50.0
    action_monitor_rate: 20.0

    allow_partial_joints_goal: true
    hardware_state_has_offset: true
    deduce_states_from_derivatives: true

    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0

    gains:
      R10_AxisRy_Hips_Flexion: {p: 100.0, i: 0.01, d: 1.0}
      R11_AxisRx_Hips_Abduction: {p: 100.0, i: 0.01, d: 1.0}
      R12_AxisRz_Hips_Rotation: {p: 100.0, i: 0.01, d: 1.0}
      R13_AxisRy_Knee_Flexion: {p: 100.0, i: 0.01, d: 1.0}
      R14_AxisRy_Ankle_Flexion: {p: 100.0, i: 0.01, d: 1.0}
      R15_AxisRx_Ankle_Abduction: {p: 100.0, i: 0.01, d: 1.0}
      R16_AxisRx_Toe_Flexion: {p: 100.0, i: 0.01, d: 1.0}

right_leg_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - R20_AxisRy_Hips_Flexion
      - R21_AxisRx_Hips_Abduction
      - R22_AxisRz_Hips_Rotation
      - R23_AxisRy_Knee_Flexion
      - R24_AxisRy_Ankle_Flexion
      - R25_AxisRx_Ankle_Abduction
      - R26_AxisRx_Toe_Flexion
    state_publish_rate: 50.0
    action_monitor_rate: 20.0

    allow_partial_joints_goal: true
    hardware_state_has_offset: true
    deduce_states_from_derivatives: true

    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0

    gains:
      R20_AxisRy_Hips_Flexion: {p: 100.0, i: 0.01, d: 1.0}
      R21_AxisRx_Hips_Abduction: {p: 100.0, i: 0.01, d: 1.0}
      R22_AxisRz_Hips_Rotation: {p: 100.0, i: 0.01, d: 1.0}
      R23_AxisRy_Knee_Flexion: {p: 100.0, i: 0.01, d: 1.0}
      R24_AxisRy_Ankle_Flexion: {p: 100.0, i: 0.01, d: 1.0}
      R25_AxisRx_Ankle_Abduction: {p: 100.0, i: 0.01, d: 1.0}
      R26_AxisRx_Toe_Flexion: {p: 100.0, i: 0.01, d: 1.0}

left_arm_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - R30_AxisRy_Shoulder_Flexion
      - R31_AxisRz_Shoulder_Rotation
      - R32_AxisRx_Shoulder_Abduction
      - R33_AxisRy_Elbow_Flexion
      - R34_AxisRz_Wrist_Rotation
      - R35_AxisRx_Wrist_Abduction
    state_publish_rate: 50.0
    action_monitor_rate: 20.0

    allow_partial_joints_goal: true
    hardware_state_has_offset: true
    deduce_states_from_derivatives: true

    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0

    gains:
      R30_AxisRy_Shoulder_Flexion: {p: 100.0, i: 0.01, d: 1.0}
      R31_AxisRz_Shoulder_Rotation: {p: 100.0, i: 0.01, d: 1.0}
      R32_AxisRx_Shoulder_Abduction: {p: 100.0, i: 0.01, d: 1.0}
      R33_AxisRy_Elbow_Flexion: {p: 100.0, i: 0.01, d: 1.0}
      R34_AxisRz_Wrist_Rotation: {p: 100.0, i: 0.01, d: 1.0}
      R35_AxisRx_Wrist_Abduction: {p: 100.0, i: 0.01, d: 1.0}

right_arm_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - R40_AxisRy_Shoulder_Flexion
      - R41_AxisRz_Shoulder_Rotation
      - R42_AxisRx_Shoulder_Abduction
      - R43_AxisRy_Elbow_Flexion
      - R44_AxisRz_Wrist_Rotation
      - R45_AxisRx_Wrist_Abduction
    state_publish_rate: 50.0
    action_monitor_rate: 20.0

    allow_partial_joints_goal: true
    hardware_state_has_offset: true
    deduce_states_from_derivatives: true

    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0

    gains:
      R40_AxisRy_Shoulder_Flexion: {p: 100.0, i: 0.01, d: 1.0}
      R41_AxisRz_Shoulder_Rotation: {p: 100.0, i: 0.01, d: 1.0}
      R42_AxisRx_Shoulder_Abduction: {p: 100.0, i: 0.01, d: 1.0}
      R43_AxisRy_Elbow_Flexion: {p: 100.0, i: 0.01, d: 1.0}
      R44_AxisRz_Wrist_Rotation: {p: 100.0, i: 0.01, d: 1.0}
      R45_AxisRx_Wrist_Abduction: {p: 100.0, i: 0.01, d: 1.0}
